name: Test and deploy site

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  test-and-deploy-site:
    name: Test and deploy site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Test project"
      uses: pyrmont/action-janet-test@v5
    - name: "Install mendoza"
      run: |
        $PREFIX/bin/jpm install mendoza
    - name: "Merge master into gh-pages"
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin gh-pages
        git checkout -b gh-pages origin/gh-pages
        git merge master --commit --no-edit --allow-unrelated-histories
    - name: "Generate site"
      run: |
        mdz clean
        mdz build docs
    - name: "Commit and push changes"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add ./docs && git commit -am "Auto-generate site" || echo "git add and commit."
        git push https://${GITHUB_ACTOR}:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages || echo "git push to origin gh-pages"
